version: "3.7"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./src/openssl/cert.pem:/etc/caddy/cert.pem"
      - "./src/openssl/key.pem:/etc/caddy/key.pem"
      # - "./caddy/data:/data"
      # - "./caddy/config:/config"
    depends_on:
      - node
  node:
    build: .
    restart: unless-stopped
    # ports:
      # - "3000:3000"
    # volumes:
      # - ".:/usr/app/"
      # - "../client/dist:/usr/app/frontend"